name: civiapp
description: "Civi App gestionale per saloni di centri estetici"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.1
  cloud_functions: ^5.1.1
  firebase_storage: ^12.3.3
  firebase_messaging: ^15.2.10
  firebase_in_app_messaging: ^0.8.1+10
  file_picker: ^8.2.1
  path_provider: ^2.1.4
  pdf: ^3.11.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.2
  flutter_app_badger: ^1.5.0
  share_plus: 12.0.0
  url_launcher: ^6.3.2
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_stripe: ^10.0.0
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/social_logo/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  min_sdk_android: 21
  android_adaptive_icon_background: "#D6D3CD"

flutter_native_splash:
  color: "#9B1D1D"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#9B1D1D"
