// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuFtp9UicSUrYvjbT1JNQ8S-OKv_6Csvs',
    appId: '1:442062945154:web:080fdd048a96cdb84e6d9b',
    messagingSenderId: '442062945154',
    projectId: 'civiapp-38b51',
    authDomain: 'civiapp-38b51.firebaseapp.com',
    storageBucket: 'civiapp-38b51.firebasestorage.app',
    measurementId: 'G-SFSQB8YH04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgWb1Ikb5ocDN73eL2ledLo0OjvOgGnUA',
    appId: '1:442062945154:android:8edeace19236d4b44e6d9b',
    messagingSenderId: '442062945154',
    projectId: 'civiapp-38b51',
    storageBucket: 'civiapp-38b51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6yjZh6tGvg2HRrlKtTl9gFh89vAFGLw',
    appId: '1:442062945154:ios:6aba05c66d9e5dd94e6d9b',
    messagingSenderId: '442062945154',
    projectId: 'civiapp-38b51',
    storageBucket: 'civiapp-38b51.firebasestorage.app',
    iosBundleId: 'com.example.civiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6yjZh6tGvg2HRrlKtTl9gFh89vAFGLw',
    appId: '1:442062945154:ios:6aba05c66d9e5dd94e6d9b',
    messagingSenderId: '442062945154',
    projectId: 'civiapp-38b51',
    storageBucket: 'civiapp-38b51.firebasestorage.app',
    iosBundleId: 'com.example.civiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuFtp9UicSUrYvjbT1JNQ8S-OKv_6Csvs',
    appId: '1:442062945154:web:d9af5142c43e56ce4e6d9b',
    messagingSenderId: '442062945154',
    projectId: 'civiapp-38b51',
    authDomain: 'civiapp-38b51.firebaseapp.com',
    storageBucket: 'civiapp-38b51.firebasestorage.app',
    measurementId: 'G-3NBLM9XEL2',
  );
}
